import type { Metadata } from "next";
import { resolveLocale } from "./lib/i18n/locale";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await resolveLocale();

  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
